#!/usr/bin/perl
open my $fh, '<', 'words';
my $words = join '', grep length, <$fh>;
close $fh;

$words =~ s/\n/","/g;
open my $out, '>', 'words.js';
print $out 'word_list = ["', $words, '"];', "\n";
close $out;
